import { z } from "zod";
import type {
  AgentChatInput,
  AgentTurnResult,
  AIProvider,
  ChatInput,
  ChatResult,
  StructuredInput,
  ToolCall,
  ToolSpec,
} from "./types.js";
import { AIUnavailableError } from "./types.js";

export interface OllamaProviderOptions {
  baseUrl?: string;
  /** If omitted, the provider auto-detects the first locally available model on first use. */
  model?: string;
  timeoutMs?: number;
  /** Context window to request. Must fit the tool schemas plus the project snapshot. */
  contextTokens?: number;
  /** Maximum tokens generated by one model call. Prevents an unbounded CPU inference. */
  numPredict?: number;
  /** Ollama duration string, e.g. "15m". Keeps weights resident without polling. */
  keepAlive?: string;
}

interface OllamaToolCallBody {
  function?: { name?: string; arguments?: unknown };
}

interface OllamaChatResponseBody {
  message?: { role: string; content: string; tool_calls?: OllamaToolCallBody[] };
  model?: string;
}

interface OllamaTagsResponseBody {
  models?: { name: string; capabilities?: string[] }[];
}

const DEFAULT_MAX_STEPS = 6;

export class OllamaProvider implements AIProvider {
  readonly isLocalModel = true;

  private readonly baseUrl: string;
  private readonly timeoutMs: number;
  private readonly contextTokens: number;
  private readonly numPredict: number;
  private readonly keepAlive: string;
  private configuredModel: string | undefined;
  private resolvedModel: string | null = null;
  private activeRequests=0;

  constructor(options: OllamaProviderOptions = {}) {
    this.baseUrl = (options.baseUrl ?? process.env.OLLAMA_BASE_URL ?? "http://127.0.0.1:11434").replace(
      /\/+$/,
      "",
    );
    this.configuredModel = options.model ?? process.env.OLLAMA_MODEL ?? undefined;
    // 45s was too tight even for a single plain status call on CPU-only local
    // hardware once the model needs a cold load (observed 65s total for an
    // 8B model's first response, ~19s of which was just loading weights).
    // Tool-calling agent turns can take several such round trips.
    this.timeoutMs = options.timeoutMs ?? (Number(process.env.OLLAMA_TIMEOUT_MS) || 120_000);
    this.contextTokens = options.contextTokens ?? (Number(process.env.OLLAMA_NUM_CTX) || 8192);
    this.numPredict = options.numPredict ?? (Number(process.env.OLLAMA_NUM_PREDICT) || 192);
    this.keepAlive = options.keepAlive ?? process.env.OLLAMA_KEEP_ALIVE ?? "15m";
  }

  async health(): Promise<{ reachable:boolean; model:string|null; contextSize:number; warm:boolean; state:"ready"|"loading"|"running"|"offline"; error:string|null }> {
    try {
      const model=await this.resolveModel();
      const controller=new AbortController(); const timer=setTimeout(()=>controller.abort(),3000);
      try {
        const response=await fetch(`${this.baseUrl}/api/ps`,{signal:controller.signal});
        const body=response.ok ? await response.json() as {models?:{name:string}[]} : {models:[]};
        const warm=body.models?.some(item=>item.name===model || item.name.split(":")[0]===model.split(":")[0]) ?? false;
        return {reachable:true,model,contextSize:this.contextTokens,warm,state:this.activeRequests>0?"running":warm?"ready":"loading",error:null};
      } finally { clearTimeout(timer); }
    } catch(err) { return {reachable:false,model:null,contextSize:this.contextTokens,warm:false,state:"offline",error:err instanceof Error?err.message:String(err)}; }
  }

  private async resolveModel(): Promise<string> {
    if (this.configuredModel) return this.configuredModel;
    if (this.resolvedModel) return this.resolvedModel;

    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), Math.min(this.timeoutMs, 5000));
    try {
      const res = await fetch(`${this.baseUrl}/api/tags`, { signal: controller.signal });
      if (!res.ok) {
        throw new AIUnavailableError(`Ollama /api/tags returned HTTP ${res.status}`);
      }
      const body = (await res.json()) as OllamaTagsResponseBody;
      const installed = body.models ?? [];
      if (installed.length === 0) {
        throw new AIUnavailableError(
          "No local Ollama models are installed. Pull one with `ollama pull qwen2.5` or set OLLAMA_MODEL.",
        );
      }

      // NEMO's agent is useless without function calling, and plenty of local
      // installs lead with something that cannot do it at all (an embedding
      // model, say). Ollama reports the capability, so honour it rather than
      // taking whatever happens to be listed first and failing later in a way
      // that looks like the agent is broken.
      const toolCapable = installed.filter((entry) => entry.capabilities?.includes("tools"));
      const chosen = (toolCapable[0] ?? installed.find((entry) => !entry.capabilities))?.name;
      if (!chosen) {
        throw new AIUnavailableError(
          `None of the installed Ollama models support tool calling (${installed.map((m) => m.name).join(", ")}). ` +
            "Pull one that does, for example `ollama pull qwen2.5`, or set OLLAMA_MODEL.",
        );
      }
      this.resolvedModel = chosen;
      return chosen;
    } catch (err) {
      if (err instanceof AIUnavailableError) throw err;
      throw new AIUnavailableError("Could not reach Ollama to list local models.", { cause: err });
    } finally {
      clearTimeout(timer);
    }
  }

  private async callChat(
    model: string,
    messages: ChatInput["messages"],
    options: { temperature?: number; format?: "json"; tools?: unknown[] },
  ): Promise<OllamaChatResponseBody> {
    this.activeRequests++;
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), this.timeoutMs);
    try {
      const res = await fetch(`${this.baseUrl}/api/chat`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        signal: controller.signal,
        body: JSON.stringify({
          model,
          messages,
          stream: false,
          keep_alive: this.keepAlive,
          ...(options.format ? { format: options.format } : {}),
          ...(options.tools ? { tools: options.tools } : {}),
          options: {
            temperature: options.temperature ?? 0.2,
            // Large context windows materially increase model-load and prompt
            // evaluation cost on CPU. Keep enough headroom for this payload,
            // while retaining the configured maximum for schema-heavy turns.
            num_ctx: contextWindowFor(messages, options.tools, this.contextTokens),
            num_predict: this.numPredict,
          },
        }),
      });
      if (!res.ok) {
        const text = await res.text().catch(() => "");
        throw new AIUnavailableError(`Ollama /api/chat returned HTTP ${res.status}: ${text.slice(0, 300)}`);
      }
      return (await res.json()) as OllamaChatResponseBody;
    } catch (err) {
      if (err instanceof AIUnavailableError) throw err;
      const isAbort = err instanceof Error && err.name === "AbortError";
      throw new AIUnavailableError(
        isAbort ? `Ollama request timed out after ${this.timeoutMs}ms` : "Could not reach Ollama.",
        { cause: err },
      );
    } finally {
      clearTimeout(timer);
      this.activeRequests--;
    }
  }

  async chat(input: ChatInput): Promise<ChatResult> {
    const model = await this.resolveModel();
    const body = await this.callChat(model, input.messages, { temperature: input.temperature });
    const text = body.message?.content?.trim();
    if (!text) {
      throw new AIUnavailableError("Ollama returned an empty response.");
    }
    return { text, model: body.model ?? model };
  }

  async structured<T>(input: StructuredInput<T>): Promise<T> {
    const model = await this.resolveModel();
    const jsonInstruction: ChatInput["messages"][number] = {
      role: "system",
      content:
        `Respond with ONLY valid JSON matching this shape${input.schemaName ? ` (${input.schemaName})` : ""}. ` +
        "No markdown, no code fences, no commentary before or after the JSON.",
    };

    const body = await this.callChat(model, [jsonInstruction, ...input.messages], {
      temperature: input.temperature,
      format: "json",
    });

    const raw = body.message?.content?.trim();
    if (!raw) {
      throw new AIUnavailableError("Ollama returned an empty response for a structured request.");
    }

    let parsedJson: unknown;
    try {
      parsedJson = JSON.parse(stripCodeFences(raw));
    } catch (err) {
      throw new AIUnavailableError("Ollama did not return valid JSON.", { cause: err });
    }

    const result = input.schema.safeParse(parsedJson);
    if (!result.success) {
      throw new AIUnavailableError(
        `Ollama's JSON did not match the expected schema: ${result.error.message}`,
      );
    }
    return result.data;
  }

  async runAgent(input: AgentChatInput): Promise<AgentTurnResult> {
    const model = await this.resolveModel();
    const maxSteps = input.maxSteps ?? DEFAULT_MAX_STEPS;
    const tools = input.tools.map(toOllamaTool);
    const messages: ChatInput["messages"] = [...input.messages];
    const toolCalls: AgentTurnResult["toolCalls"] = [];
    const offered = new Set(input.tools.map((tool) => tool.name));
    /** Signatures of calls already run this turn, so a repeated print is not a repeated write. */
    const executed = new Set<string>();

    for (let step = 0; step < maxSteps; step++) {
      const body = await this.callChat(model, messages, { temperature: input.temperature, tools });
      const message = body.message;
      if (!message) throw new AIUnavailableError("Ollama returned no message.");

      const rawCalls = message.tool_calls ?? [];
      const text = message.content?.trim() ?? "";

      // Small local models routinely *print* a tool call instead of emitting it
      // in `tool_calls`: llama3.2:1b answers "raise the priority" with the
      // literal text {"name":"setPriority","parameters":{...}}. Discarding that
      // reads downstream as "the model refused to act" when it actually decided
      // correctly, so recover the intent. Only names that were offered this turn
      // are accepted, and only calls that have not already run, which keeps
      // prose that merely mentions a tool from becoming an action or a loop.
      const calls: ToolCall[] =
        rawCalls.length > 0
          ? rawCalls.map((raw) => ({
              name: raw.function?.name ?? "",
              arguments: unwrapCallEnvelope(normalizeToolArgs(raw.function?.arguments), offered),
            }))
          : parseInlineToolCalls(text, offered).filter((call) => !executed.has(signature(call)));

      if (calls.length === 0) {
        if (!text) throw new AIUnavailableError("Ollama returned an empty response.");
        return { text, toolCalls, model: body.model ?? model, modelCalls:step+1 };
      }

      messages.push({ role: "assistant", content: message.content ?? "" });

      for (const call of calls) {
        executed.add(signature(call));
        const result = await input.executeTool(call);
        toolCalls.push({ call, result });
        messages.push({ role: "tool", name: call.name, content: JSON.stringify(result) });
        if(calls.length===1 && input.finishAfterTool){
          const final=input.finishAfterTool(call,result);
          if(final) return {text:final,toolCalls,model:body.model??model,modelCalls:step+1};
        }
      }
    }

    throw new AIUnavailableError(`AI PM did not finish planning within ${maxSteps} tool-calling step(s).`);
  }
}

function contextWindowFor(messages: ChatInput["messages"], tools: unknown[] | undefined, maximum: number) {
  // JSON characters / 3 is deliberately conservative for English plus tool
  // schemas; the extra 512 tokens cover Ollama's chat/tool template.
  const estimatedTokens = Math.ceil(JSON.stringify({ messages, tools }).length / 3) + 512;
  const requested = estimatedTokens <= 2048 ? 2048 : estimatedTokens <= 4096 ? 4096 : 8192;
  return Math.min(maximum, requested);
}

function toOllamaTool(tool: ToolSpec) {
  return {
    type: "function",
    function: {
      name: tool.name,
      description: tool.description,
      parameters: tool.parameters,
    },
  };
}

/** The name in an envelope, which models spell as `name` or as a string `function`. */
function envelopeName(node: Record<string, unknown>): string | undefined {
  if (typeof node.name === "string") return node.name;
  if (typeof node.function === "string") return node.function;
  return undefined;
}

/**
 * Undoes the envelope small models nest inside their own arguments: instead of
 * {"title":"..."} they send {"type":"function","name":"createIssue","parameters":
 * {"title":"..."}}. Left alone the tool sees no title and a type of "function",
 * and reports a schema error for a decision that was actually correct. Only
 * unwrapped when the inner name is a tool that was really offered, so genuine
 * arguments that merely contain a "name" are untouched.
 */
export function unwrapCallEnvelope(args: Record<string, unknown>, offered: Set<string>): Record<string, unknown> {
  let current = args;
  for (let depth = 0; depth < 2; depth++) {
    const name = envelopeName(current);
    if (!name || !offered.has(name)) return current;
    const inner = current.parameters ?? current.arguments ?? current.args;
    if (!inner || typeof inner !== "object" || Array.isArray(inner)) return current;
    current = inner as Record<string, unknown>;
  }
  return current;
}

const MAX_INLINE_TOOL_CALLS = 3;

const signature = (call: ToolCall) => `${call.name}:${JSON.stringify(call.arguments)}`;

/** Every balanced top-level {...} span in a blob of prose, string-aware. */
function jsonCandidates(text: string): string[] {
  const found: string[] = [];
  let depth = 0;
  let start = -1;
  let inString = false;
  let escaped = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i]!;
    if (inString) {
      if (escaped) escaped = false;
      else if (ch === "\\") escaped = true;
      else if (ch === '"') inString = false;
      continue;
    }
    if (ch === '"') inString = true;
    else if (ch === "{") {
      if (depth === 0) start = i;
      depth++;
    } else if (ch === "}") {
      depth = Math.max(0, depth - 1);
      if (depth === 0 && start >= 0) {
        found.push(text.slice(start, i + 1));
        start = -1;
      }
    }
  }
  return found;
}

/**
 * Repairs the two malformations small models produce most when hand-writing a
 * call: unquoted keys and unquoted string values ({"issueKey":ECOM-5}). Only
 * ever applied after a strict parse has already failed.
 */
function repairJson(candidate: string): string {
  return candidate
    .replace(/([{,]\s*)([A-Za-z_][A-Za-z0-9_]*)(\s*:)/g, '$1"$2"$3')
    .replace(/:(\s*)([A-Za-z_][A-Za-z0-9_.-]*)(\s*[,}])/g, (match, space: string, word: string, tail: string) =>
      /^(true|false|null)$/i.test(word) ? match : `:${space}"${word}"${tail}`,
    );
}

/**
 * Recovers tool calls a model wrote into its message text. Accepts the shapes
 * seen in the wild -- {"name":..,"parameters":..}, {"name":..,"arguments":..},
 * {"function":{...}} -- optionally wrapped in code fences or <tool_call> tags.
 */
export function parseInlineToolCalls(text: string, offered: Set<string>): ToolCall[] {
  if (!text || offered.size === 0) return [];
  const cleaned = text.replace(/<\/?tool_call>|<\|python_tag\|>|```(?:json)?/gi, " ");
  const calls: ToolCall[] = [];
  for (const candidate of jsonCandidates(cleaned)) {
    let parsed: unknown;
    try {
      parsed = JSON.parse(candidate);
    } catch {
      try {
        parsed = JSON.parse(repairJson(candidate));
      } catch {
        continue;
      }
    }
    if (!parsed || typeof parsed !== "object") continue;
    const node = parsed as Record<string, unknown>;
    const fn = (node.function && typeof node.function === "object" ? node.function : node) as Record<string, unknown>;
    const name = envelopeName(fn);
    if (!name || !offered.has(name)) continue;
    calls.push({
      name,
      arguments: unwrapCallEnvelope(
        normalizeToolArgs(fn.parameters ?? fn.arguments ?? fn.args ?? node.parameters ?? node.arguments),
        offered,
      ),
    });
    if (calls.length >= MAX_INLINE_TOOL_CALLS) break;
  }
  return calls;
}

function normalizeToolArgs(args: unknown): Record<string, unknown> {
  if (args && typeof args === "object") return args as Record<string, unknown>;
  if (typeof args === "string") {
    try {
      return JSON.parse(args);
    } catch {
      return {};
    }
  }
  return {};
}

function stripCodeFences(text: string): string {
  const trimmed = text.trim();
  const fenced = trimmed.match(/^```(?:json)?\s*([\s\S]*?)\s*```$/i);
  return fenced ? fenced[1]!.trim() : trimmed;
}

// Re-exported so callers can validate their own structured schemas without
// importing zod directly if they don't otherwise need it.
export { z };
