import type { FastifyInstance } from "fastify";
import { getDb, intelligenceRepo, issuesRepo, projectsRepo, repositoriesRepo } from "@ai-pm/database";
import { notFound } from "../lib/errors.js";
import { DEFAULT_AUTONOMY, getNemoToday, getProjectIntelligence, ingestAndReconcile } from "../lib/intelligence.js";
import { detectTestCommand, discoverTestSuites, runDetectedTests } from "../lib/evidence-intelligence.js";

const scans = new Map<string, Promise<unknown>>();
function boundedScan(projectId:string){ const current=scans.get(projectId); if(current)return current; const task=ingestAndReconcile(getDb(),projectId).finally(()=>scans.delete(projectId)); scans.set(projectId,task); return task; }

export async function intelligenceRoutes(app:FastifyInstance){ const db=getDb();
  app.post<{Params:{projectId:string}}>("/projects/:projectId/intelligence/import",async req=>{if(!projectsRepo.getProject(db,req.params.projectId))throw notFound("Project",req.params.projectId); return boundedScan(req.params.projectId);});
  app.post<{Params:{projectId:string}}>("/projects/:projectId/intelligence/reconcile",async req=>{if(!projectsRepo.getProject(db,req.params.projectId))throw notFound("Project",req.params.projectId); return boundedScan(req.params.projectId);});
  app.get<{Params:{projectId:string}}>("/projects/:projectId/intelligence",async req=>{if(!projectsRepo.getProject(db,req.params.projectId))throw notFound("Project",req.params.projectId); return getProjectIntelligence(db,req.params.projectId);});
  app.get("/intelligence/today",async()=>getNemoToday(db));
  app.get<{Params:{projectId:string}}>("/projects/:projectId/intelligence/settings",async req=>intelligenceRepo.getAutonomySettings(db,req.params.projectId)??DEFAULT_AUTONOMY);
  app.put<{Params:{projectId:string};Body:unknown}>("/projects/:projectId/intelligence/settings",async req=>{if(!projectsRepo.getProject(db,req.params.projectId))throw notFound("Project",req.params.projectId); return intelligenceRepo.setAutonomySettings(db,req.params.projectId,req.body);});
  app.post<{Params:{projectId:string;actionId:string}}>("/projects/:projectId/intelligence/actions/:actionId/approve",async req=>{const action=intelligenceRepo.getAction(db,req.params.actionId);if(!action||action.projectId!==req.params.projectId)throw notFound("Intelligence action",req.params.actionId);if(action.status!=="proposed")return action;const next=(action.next??{}) as Record<string,unknown>;if(action.actionType==="issue.move_to_review"&&typeof next.issueId==="string")issuesRepo.reviewIssue(db,next.issueId);return intelligenceRepo.resolveAction(db,req.params.actionId,"applied");});
  app.post<{Params:{projectId:string;actionId:string}}>("/projects/:projectId/intelligence/actions/:actionId/reject",async req=>{const action=intelligenceRepo.getAction(db,req.params.actionId);if(!action||action.projectId!==req.params.projectId)throw notFound("Intelligence action",req.params.actionId);return intelligenceRepo.resolveAction(db,req.params.actionId,"rejected");});
  app.post<{Params:{projectId:string};Body:{correction:string;findingId?:string;context?:Record<string,unknown>}}>("/projects/:projectId/intelligence/corrections",async req=>{if(!projectsRepo.getProject(db,req.params.projectId))throw notFound("Project",req.params.projectId);const correction=req.body?.correction?.trim();if(!correction)throw new Error("Correction is required");const id=intelligenceRepo.recordAction(db,{projectId:req.params.projectId,actionType:"human.correction",status:"applied",impact:"LOW",confidence:1,evidence:[correction],policy:{scope:"project",source:"human"},next:{findingId:req.body.findingId??null,context:req.body.context??{}}});return intelligenceRepo.getAction(db,id);});
  app.get<{Params:{projectId:string}}>("/projects/:projectId/intelligence/documentation",async req=>{if(!projectsRepo.getProject(db,req.params.projectId))throw notFound("Project",req.params.projectId);const state=getProjectIntelligence(db,req.params.projectId);return{generatedAt:new Date().toISOString(),project:projectsRepo.getProject(db,req.params.projectId),understanding:state.understanding,confirmedAndAutomaticActions:state.actions.filter(action=>action.status==="applied"),pendingProposals:state.actions.filter(action=>action.status==="proposed"),corrections:state.actions.filter(action=>action.actionType==="human.correction")};});
  app.post<{Params:{projectId:string};Body:Omit<intelligenceRepo.ReviewV2Input,"projectId">}>("/projects/:projectId/intelligence/reviews",async req=>{if(!projectsRepo.getProject(db,req.params.projectId))throw notFound("Project",req.params.projectId);return intelligenceRepo.recordReviewV2(db,{projectId:req.params.projectId,...req.body});});
  app.get<{Params:{projectId:string}}>("/projects/:projectId/intelligence/reviews",async req=>({reviews:intelligenceRepo.listReviewsV2(db,req.params.projectId),metrics:intelligenceRepo.evaluationMetrics(db,req.params.projectId)}));
  app.get<{Params:{projectId:string}}>("/projects/:projectId/intelligence/reviews/export",async req=>{if(!projectsRepo.getProject(db,req.params.projectId))throw notFound("Project",req.params.projectId);return intelligenceRepo.exportReviewDataset(db,req.params.projectId);});
  app.get<{Params:{projectId:string}}>("/projects/:projectId/intelligence/tests/detect",async req=>{const repo=repositoriesRepo.getRepositoryByProject(db,req.params.projectId);if(!repo)throw notFound("Repository",req.params.projectId);return{mode:"DETECT_ONLY",suites:discoverTestSuites(repo.path)};});
  app.post<{Params:{projectId:string};Body:{timeoutMs?:number}}>("/projects/:projectId/intelligence/tests/run",async req=>{const repo=repositoriesRepo.getRepositoryByProject(db,req.params.projectId);if(!repo)throw notFound("Repository",req.params.projectId);const settings={...DEFAULT_AUTONOMY,...(intelligenceRepo.getAutonomySettings(db,req.params.projectId)??{})};const evidence=await runDetectedTests(repo.path,detectTestCommand(repo.path),{enabled:settings.testExecution===true,timeoutMs:Math.min(300_000,Math.max(1_000,req.body?.timeoutMs??120_000))});intelligenceRepo.recordTestEvidence(db,req.params.projectId,repo.id,evidence);return evidence;});
}
