import type Database from "better-sqlite3";
import type{ProjectState,RoutingDecision}from"@ai-pm/shared";
import{decisionsRepo,milestonesRepo,projectsRepo}from"@ai-pm/database";
import{formatDeterministicStatus}from"./ai.js";
import{buildPortfolioState}from"./portfolio.js";

export interface FallbackInput{db:Database.Database;projectId:string;routing:RoutingDecision;state:ProjectState;reason?:string}
const unavailable=(reason?:string)=>`AI unavailable${reason?` (${reason})`:""} — using deterministic fallback.`;
export function buildDeterministicFallback({db,projectId,routing,state,reason}:FallbackInput):string{
  if(routing.intent==="project.status")return `${unavailable(reason)}\n\n${formatDeterministicStatus(state,{projectMode:routing.projectMode})}`;
  const decisions=decisionsRepo.listDecisionsByProject(db,projectId);const milestones=milestonesRepo.listMilestonesByProject(db,projectId).filter(m=>m.confirmed);
  if(routing.intent==="memory.query")return[unavailable(reason),"","ANSWER",decisions.length?decisions.slice(0,10).map(d=>`- ${d.title}: ${d.decision??"Recorded decision"}`).join("\n"):"No matching confirmed decision is stored.","","EVIDENCE",`${decisions.length} confirmed project decision(s) available.`].join("\n");
  if(routing.intent==="history.query")return[unavailable(reason),"","CONFIRMED HISTORY",milestones.length?milestones.slice(0,10).map(m=>`- ${m.title} (${m.status})`).join("\n"):"No confirmed milestones are stored yet.","","SYNTHESIS","Deeper historical synthesis is unavailable while AI is offline."].join("\n");
  if(routing.projectMode==="BOOTSTRAP"&&routing.intent.startsWith("bootstrap.")){const project=projectsRepo.getProjectOrThrow(db,projectId);const known=[project.description&&`Project description: ${project.description}`,decisions.length&&`${decisions.length} stored decision(s)`,milestones.length&&`${milestones.length} confirmed milestone(s)`].filter(Boolean);const missing=[!project.description&&"product description",decisions.length===0&&"architecture/product decisions",milestones.length===0&&"milestones",state.metrics.totalIssues===0&&"backlog items"].filter(Boolean);return[unavailable(reason),"","PROJECT",`${project.name} is a new project currently in planning.`,"","CURRENT STAGE",routing.intent==="bootstrap.architecture"?"Architecture planning.":routing.intent==="bootstrap.define_mvp"?"Product definition / MVP planning.":"Product definition.","","KNOWN",known.length?known.map(x=>`- ${x}`).join("\n"):"- Only the project name is stored.","","NOT YET DEFINED",missing.length?missing.map(x=>`- ${x}`).join("\n"):"- No missing core planning artifacts detected.","","NEXT ACTION","Continue planning when AI is available, or review and create the structured decisions, milestones, and backlog artifacts already supported by NEMO.","","No backlog items have been created yet; this does not mean the project has no work remaining."].join("\n");}
  return[unavailable(reason),"",`Route: ${routing.intent}`,"Known project facts remain available, but deeper synthesis is unavailable.","",`NEXT ACTION\nRetry when AI is available or use the deterministic project records.`].join("\n");
}
export function buildPortfolioFallback(db:Database.Database,reason?:string){const state=buildPortfolioState(db);const openIssues=state.projects.reduce((n,p)=>n+p.openIssues,0),activeSprints=state.projects.filter(p=>p.activeSprint).length;return{runId:null,reply:[unavailable(reason),"","FACTS AVAILABLE",`Projects: ${state.projects.length}`,`Open issues: ${openIssues}`,`Active sprints: ${activeSprints}`,"","AI PRIORITIZATION UNAVAILABLE","Project facts are available, but cross-project prioritization requires AI."].join("\n"),actions:[],appliedResults:[],plan:null,toolCalls:[],status:"done" as const,runtime:{modelCalls:0,toolsOffered:[],route:"portfolio.analyze",routingConfidence:1,projectMode:"ACTIVE",intent:"portfolio.analyze",capabilities:["portfolio_read"],repositoryContext:false,codeContext:false,contextSources:["portfolio-state"],agentSteps:0}};}
