import { execFile } from "node:child_process";
import { promisify } from "node:util";
import fs from "node:fs";
import path from "node:path";
import type { BranchEvidence, EvidenceSignal, FileEvolution, ModuleEvolution, RepositorySnapshot, TestEvidence } from "@ai-pm/shared";
const execFileAsync=promisify(execFile);const DAY=86_400_000;
async function command(exe:string,args:string[],cwd:string,timeout=10_000){try{const result=await execFileAsync(exe,args,{cwd,timeout,maxBuffer:2_000_000,windowsHide:true});return{ok:true,stdout:result.stdout,stderr:result.stderr};}catch(error){const e=error as Error&{stdout?:string;stderr?:string;killed?:boolean;code?:number|string;signal?:string};return{ok:false,stdout:e.stdout??"",stderr:e.stderr??e.message,timeout:e.killed===true||e.signal==="SIGTERM"||e.code==="ETIMEDOUT"||/timeout/i.test(e.message),code:e.code};}}
function moduleOf(file:string){const p=file.replaceAll("\\","/").split("/");if(p[0]==="src"&&p.length>2)return p.slice(0,p[1]==="back"?3:2).join("/");if(["apps","packages","services"].includes(p[0]??"")&&p.length>1)return p.slice(0,2).join("/");return p.slice(0,Math.min(2,p.length)).join("/");}
export async function analyzeFileEvolution(snapshot:RepositorySnapshot):Promise<{files:FileEvolution[];modules:ModuleEvolution[]}>{const raw=await command("git",["log","--all","-n","300","--date=iso-strict","--pretty=format:@@%H|%aI","--name-only"],snapshot.repositoryPath,20_000);const history=new Map<string,{firstSeen:string;lastSeen:string;firstCommit:string;lastCommit:string}>();let hash="",date="";for(const line of raw.stdout.split(/\r?\n/)){if(line.startsWith("@@")){[hash,date]=line.slice(2).split("|") as[string,string];continue;}const file=line.trim().replaceAll("\\","/");if(!file||!snapshot.files.includes(file))continue;const old=history.get(file);if(!old)history.set(file,{firstSeen:date,lastSeen:date,firstCommit:hash,lastCommit:hash});else{old.firstSeen=date;old.firstCommit=hash;}}
 const files=snapshot.files.map(file=>{const h=history.get(file);const signals:EvidenceSignal[]=[{type:"CURRENT_FILE",strength:"MEDIUM",source:"filesystem",detail:file}];if(/migrations?\//i.test(file))signals.push({type:"MIGRATION",strength:"STRONG",source:"path",detail:file});if(/(test|spec)/i.test(file))signals.push({type:"TEST",strength:"MEDIUM",source:"path",detail:file});if(/route|controller|api\//i.test(file))signals.push({type:"API_SURFACE",strength:"MEDIUM",source:"path",detail:file});return{file,module:moduleOf(file),firstSeen:h?.firstSeen??null,lastSeen:h?.lastSeen??null,firstCommit:h?.firstCommit??null,lastCommit:h?.lastCommit??null,signals};});
 const grouped=new Map<string,FileEvolution[]>();for(const file of files)grouped.set(file.module,[...(grouped.get(file.module)??[]),file]);const modules=[...grouped].map(([module,items])=>{const dates=items.flatMap(f=>[f.firstSeen,f.lastSeen]).filter((d):d is string=>Boolean(d)).sort();const tests=items.filter(f=>f.signals.some(s=>s.type==="TEST")).map(f=>f.file);const migrations=items.filter(f=>f.signals.some(s=>s.type==="MIGRATION")).map(f=>f.file);const evidence:EvidenceSignal[]=[{type:"FILE_GROUP",strength:items.length>=3?"MEDIUM":"WEAK",source:"filesystem",detail:`${items.length} related files`}];if(tests.length)evidence.push({type:"RELATED_TESTS",strength:"MEDIUM",source:"filesystem",detail:`${tests.length} test files`});if(migrations.length)evidence.push({type:"RELATED_MIGRATIONS",strength:"STRONG",source:"filesystem",detail:`${migrations.length} migrations`});return{module,files:items.length,firstObservableEvidence:dates[0]??null,lastObservableEvidence:dates.at(-1)??null,tests,migrations,confidence:migrations.length&&tests.length?"HIGH_CONFIDENCE":items.length>=3?"INFERRED":"UNKNOWN",evidence} satisfies ModuleEvolution;});return{files,modules};}

export function fuseEvidence(signals:EvidenceSignal[]){const strong=signals.filter(s=>s.strength==="STRONG");const medium=signals.filter(s=>s.strength==="MEDIUM");const weak=signals.filter(s=>s.strength==="WEAK");const confidence=strong.length>=1&&(medium.length>=1||strong.length>=2)?"HIGH_CONFIDENCE":strong.length===1||medium.length>=2?"INFERRED":weak.length||medium.length?"UNKNOWN":"UNKNOWN";return{confidence,signals,summary:{strong:strong.length,medium:medium.length,weak:weak.length}};}

export async function analyzeBranches(repoPath:string,staleDays=60):Promise<BranchEvidence[]>{const defaultRaw=await command("git",["symbolic-ref","refs/remotes/origin/HEAD","--short"],repoPath);let defaultBranch=defaultRaw.stdout.trim();if(!defaultBranch){for(const candidate of["main","master","develop"]){if((await command("git",["show-ref","--verify","--quiet",`refs/heads/${candidate}`],repoPath)).ok){defaultBranch=candidate;break;}}}if(!defaultBranch)return[];const refs=await command("git",["for-each-ref","--format=%(refname:short)|%(committerdate:iso-strict)","refs/heads","refs/remotes/origin"],repoPath);const results:BranchEvidence[]=[];for(const line of refs.stdout.split(/\r?\n/).filter(Boolean)){const[name,lastActivity]=line.split("|");if(!name||name===defaultBranch||name===defaultBranch.replace(/^origin\//,"")||name==="origin/HEAD")continue;const counts=await command("git",["rev-list","--left-right","--count",`${defaultBranch}...${name}`],repoPath);if(!counts.ok){results.push({name,defaultBranch,state:"UNKNOWN",ahead:0,behind:0,lastActivity:lastActivity??null,changedFiles:[],confidence:0});continue;}const[behind=0,ahead=0]=counts.stdout.trim().split(/\s+/).map(Number);const changed=(await command("git",["diff","--name-only",`${defaultBranch}...${name}`],repoPath)).stdout.split(/\r?\n/).filter(Boolean).slice(0,100);const stale=lastActivity?Date.now()-new Date(lastActivity).getTime()>staleDays*DAY:true;const state=ahead===0?(behind>0?"MERGED":"NO_UNIQUE_WORK"):(stale?"STALE_DIVERGED":"ACTIVE_DIVERGED");results.push({name,defaultBranch,state,ahead,behind,lastActivity:lastActivity??null,changedFiles:changed,confidence:.98});}return results;}

export interface DetectedTestCommand{adapter:string;executable:string;args:string[];command:string[];recognized:boolean;}
export function detectTestCommand(repoPath:string):DetectedTestCommand|null{const pkg=path.join(repoPath,"package.json");if(fs.existsSync(pkg)){try{const json=JSON.parse(fs.readFileSync(pkg,"utf8")) as{scripts?:Record<string,string>;packageManager?:string};if(json.scripts?.test&&!/echo .*(no test|error)/i.test(json.scripts.test)){const manager=json.packageManager?.startsWith("pnpm")?"pnpm":fs.existsSync(path.join(repoPath,"pnpm-lock.yaml"))?"pnpm":fs.existsSync(path.join(repoPath,"yarn.lock"))?"yarn":"npm";const args=["test"];return{adapter:"NodeTestAdapter",executable:manager,args,command:[manager,...args],recognized:true};}}catch{return null;}}if(fs.existsSync(path.join(repoPath,"pytest.ini"))||fs.existsSync(path.join(repoPath,"pyproject.toml")))return{adapter:"PythonTestAdapter",executable:"python",args:["-m","pytest","-q"],command:["python","-m","pytest","-q"],recognized:true};if(fs.existsSync(path.join(repoPath,"go.mod")))return{adapter:"GoTestAdapter",executable:"go",args:["test","./..."],command:["go","test","./..."],recognized:true};if(fs.existsSync(path.join(repoPath,"Cargo.toml")))return{adapter:"RustTestAdapter",executable:"cargo",args:["test","--","--quiet"],command:["cargo","test","--","--quiet"],recognized:true};const solution=fs.readdirSync(repoPath).find(f=>f.endsWith(".sln"));if(solution)return{adapter:"DotnetTestAdapter",executable:"dotnet",args:["test",solution,"--no-restore"],command:["dotnet","test",solution,"--no-restore"],recognized:true};return null;}
export interface DetectedTestSuite{relativePath:string;detected:DetectedTestCommand|null;}
function detectSuiteCommand(cwd:string){const detected=detectTestCommand(cwd);if(detected)return detected;const solution=fs.readdirSync(cwd).find(file=>file.endsWith(".slnx"));return solution?{adapter:"DotnetTestAdapter",executable:"dotnet",args:["test",solution,"--no-restore"],command:["dotnet","test",solution,"--no-restore"],recognized:true}:null;}
export function discoverTestSuites(repoPath:string,limit=100):DetectedTestSuite[]{const candidates=new Set<string>([repoPath]);const rootPackage=path.join(repoPath,"package.json");if(fs.existsSync(rootPackage)){try{const pkg=JSON.parse(fs.readFileSync(rootPackage,"utf8"))as{workspaces?:string[]|{packages?:string[]}};const patterns=Array.isArray(pkg.workspaces)?pkg.workspaces:pkg.workspaces?.packages??[];for(const pattern of patterns){const base=pattern.replace(/\/\*.*$/,"");const absolute=path.join(repoPath,base);if(!fs.existsSync(absolute))continue;for(const entry of fs.readdirSync(absolute,{withFileTypes:true}))if(entry.isDirectory())candidates.add(path.join(absolute,entry.name));}}catch{/* malformed manifests are evidence-unavailable */}}for(const base of["apps","packages","services","src"]){const absolute=path.join(repoPath,base);if(!fs.existsSync(absolute))continue;for(const entry of fs.readdirSync(absolute,{withFileTypes:true}))if(entry.isDirectory())candidates.add(path.join(absolute,entry.name));}return[...candidates].slice(0,limit).map(cwd=>({relativePath:path.relative(repoPath,cwd).replaceAll("\\","/")||".",detected:detectSuiteCommand(cwd)}));}
const ALLOWED=new Set(["npm","pnpm","yarn","node","python","go","cargo","dotnet"]);
export async function runDetectedTests(repoPath:string,detected:DetectedTestCommand|null,options:{enabled:boolean;timeoutMs?:number}):Promise<TestEvidence>{const timestamp=new Date().toISOString();if(!detected)return{adapter:"none",command:[],status:"UNAVAILABLE",durationMs:0,summary:"No allowlisted test configuration detected.",failedTests:[],timestamp};if(!options.enabled)return{adapter:detected.adapter,command:detected.command,status:"NOT_RUN",durationMs:0,summary:"Detected only; execution is disabled by project policy.",failedTests:[],timestamp};if(!detected.recognized||!ALLOWED.has(detected.executable)||detected.args.some(a=>/[;&|`$<>]/.test(a)))return{adapter:detected.adapter,command:detected.command,status:"UNAVAILABLE",durationMs:0,summary:"Command rejected by the test allowlist.",failedTests:[],timestamp};const started=performance.now();const runtimeExecutable=process.platform==="win32"&&["npm","pnpm","yarn"].includes(detected.executable)?`${detected.executable}.cmd`:detected.executable;const result=await command(runtimeExecutable,detected.args,repoPath,options.timeoutMs??120_000);const durationMs=Math.round(performance.now()-started);const output=`${result.stdout}\n${result.stderr}`.slice(-20_000);const failedTests=output.split(/\r?\n/).filter(l=>/\b(fail(ed|ure)?|error)\b/i.test(l)).slice(0,30);return{adapter:detected.adapter,command:detected.command,status:result.timeout?"TIMEOUT":result.ok?"PASS":"FAIL",durationMs,summary:output.slice(-2000),failedTests,timestamp};}

export function clusterQuality(cluster:{files:string[];commits:string[];module:string}){const moduleMatches=cluster.files.filter(f=>moduleOf(f)===cluster.module).length;const moduleCohesion=cluster.files.length?moduleMatches/cluster.files.length:0;const roots=new Set(cluster.files.map(moduleOf));const internalFileCohesion=cluster.files.length?1/roots.size:0;const tooLarge=cluster.files.length>40||cluster.commits.length>25;const flags:string[]=[];if(moduleCohesion<.65||internalFileCohesion<.5)flags.push("LOW_COHESION");if(tooLarge)flags.push("TOO_LARGE");if(cluster.files.length<2&&cluster.commits.length<2)flags.push("INSUFFICIENT_EVIDENCE");return{internalFileCohesion,moduleCohesion,tooLarge,flags};}
