import fs from "node:fs";
import path from "node:path";
import type { EvidenceConfidence, RepositorySnapshot } from "@ai-pm/shared";
const WEAK=/^(fix|update|cleanup|changes?|wip|test|merge)\W*$/i;
type WorkType="EPIC"|"FEATURE"|"TASK"|"BUG"|"REFACTOR"|"DEVOPS"|"DOCUMENTATION";
export interface WorkCluster{title:string;type:WorkType;module:string;status:"historical"|"current"|"future";commits:string[];files:string[];from:string|null;to:string|null;confidence:EvidenceConfidence;evidence:string[];}
function safeRead(file:string){try{const stat=fs.statSync(file);return stat.size<=256_000?fs.readFileSync(file,"utf8"):"";}catch{return"";}}
function moduleOf(file:string|undefined){if(!file)return"repository";const p=file.split("/");if(p[0]==="src"&&p.length>2)return p.slice(0,p[1]==="back"?3:2).join("/");if(["apps","packages","services"].includes(p[0]??"")&&p.length>1)return p.slice(0,2).join("/");return p.slice(0,Math.min(2,p.length)).join("/");}
function workTitle(subjects:string[],module:string){const useful=subjects.find(s=>!WEAK.test(s.trim())&&!/^merge/i.test(s));return(useful??`${module} development`).replace(/^\w+-\d+\s*[:\-]?\s*/i,"").slice(0,100);}
function classify(subjects:string[],files:string[]):WorkType{const text=subjects.join(" ");if(/fix|bug|crash|error|repair|hardening/i.test(text))return"BUG";if(/refactor|cleanup|restructur/i.test(text))return"REFACTOR";if(files.length>0&&files.every(f=>/\.(md|txt)$|docs?\//i.test(f)))return"DOCUMENTATION";if(files.some(f=>/\.github|docker|deploy|terraform|k8s|infra|ci\//i.test(f)))return"DEVOPS";if(/feat|add|implement|create|build/i.test(text))return"FEATURE";return"TASK";}
export function clusterRepositoryWork(snapshot:RepositorySnapshot):WorkCluster[]{
 const byModule=new Map<string,typeof snapshot.recentCommits>();for(const commit of snapshot.recentCommits){if(/^merge\b/i.test(commit.subject)&&commit.changedFiles.length===0)continue;const module=moduleOf(commit.changedFiles[0]);byModule.set(module,[...(byModule.get(module)??[]),commit]);}const clusters:WorkCluster[]=[];
 for(const[module,commits]of byModule){let group:typeof commits=[];const flush=()=>{if(!group.length)return;const subjects=group.map(c=>c.subject);const files=[...new Set(group.flatMap(c=>c.changedFiles))].slice(0,40);const meaningful=subjects.filter(s=>!WEAK.test(s)).length;const latest=group.at(-1)?.timestamp??null;const touchedNow=files.some(file=>snapshot.uncommittedFiles?.includes(file));clusters.push({title:workTitle(subjects,module),type:classify(subjects,files),module,status:touchedNow?"current":"historical",commits:group.map(c=>c.hash),files,from:group[0]?.timestamp??null,to:latest,confidence:meaningful>1||files.length>2?"HIGH_CONFIDENCE":meaningful===1?"INFERRED":"UNKNOWN",evidence:[`${group.length} related commit(s)`,`${files.length} overlapping file(s)`,`module: ${module}`,...(touchedNow?["working-tree evidence"]:[])]});group=[];};for(const commit of commits){const previous=group.at(-1);if(previous&&Math.abs(new Date(commit.timestamp).getTime()-new Date(previous.timestamp).getTime())>1000*60*60*24*21)flush();group.push(commit);}flush();}
 for(const cluster of clusters)cluster.status="historical";
 if(snapshot.uncommittedFiles?.length){const files=snapshot.uncommittedFiles;if(files.length)clusters.unshift({title:"Uncommitted working-tree changes",type:"TASK",module:moduleOf(files[0]),status:"current",commits:[],files,from:null,to:snapshot.scannedAt,confidence:"CONFIRMED",evidence:[`${files.length} uncommitted file(s)`,"Git working-tree status"]});}
 return clusters.sort((a,b)=>String(b.to).localeCompare(String(a.to))).slice(0,50);
}
export function buildUnderstandingReport(snapshot:RepositorySnapshot){
 const readme=snapshot.importantFiles.find(f=>/(^|\/)readme/i.test(f));const readmeText=readme?safeRead(path.join(snapshot.repositoryPath,readme)):"";const purpose=readmeText.split(/\r?\n/).map(s=>s.replace(/^#+\s*/,"").trim()).find(s=>s.length>30&&!/^(!|\[)/.test(s))??null;const work=clusterRepositoryWork(snapshot);const active=work.filter(w=>w.status==="current");const historical=work.filter(w=>w.status==="historical");const debt=snapshot.todos.length?Array.from(new Set(snapshot.todos.map(t=>moduleOf(t.file)))).map(module=>({module,count:snapshot.todos.filter(t=>moduleOf(t.file)===module).length,evidence:"TODO/FIXME markers"})):[];
 const risks:Array<{title:string;confidence:EvidenceConfidence;evidence:string[]}>=[];if(snapshot.tests.length===0)risks.push({title:"No test files detected",confidence:"CONFIRMED",evidence:["Deterministic file scan"]});if(snapshot.health.todos>10)risks.push({title:"Concentrated technical-debt markers",confidence:"HIGH_CONFIDENCE",evidence:[`${snapshot.health.todos} TODO/FIXME markers`]});if(snapshot.health.uncommittedChanges>0)risks.push({title:"Uncommitted repository changes",confidence:"CONFIRMED",evidence:[`${snapshot.health.uncommittedChanges} changed file(s)`]});const nextActions=[...risks.map(r=>({action:`Investigate: ${r.title}`,why:r.evidence.join(", "),urgency:"HIGH",confidence:r.confidence})),...active.slice(0,3).map(w=>({action:`Review current work: ${w.title}`,why:w.evidence.join(", "),urgency:"MEDIUM",confidence:w.confidence}))].slice(0,3);
 return{project:{purpose:purpose??"UNKNOWN",purposeConfidence:purpose?"HIGH_CONFIDENCE":"UNKNOWN",technologies:snapshot.technologies,architecture:snapshot.modules.length>1?`Modular repository with ${snapshot.modules.length} top-level modules`:"Single-root repository",modules:snapshot.modules,currentBranch:snapshot.currentBranch,recentActivity:snapshot.recentCommits.slice(-10),releases:snapshot.tags,tests:{count:snapshot.tests.length,files:snapshot.tests.slice(0,20)},deployment:snapshot.deployments,documentation:{quality:readmeText.length>1000?"GOOD":readmeText?"LIMITED":"UNKNOWN",files:snapshot.importantFiles.filter(f=>/readme|docs|changelog/i.test(f))}},currentState:{likelyCompleted:historical,likelyActive:active,potentiallyUnfinished:active.filter(w=>w.confidence!=="UNKNOWN"),untrackedWork:active,technicalDebt:debt,risks},work,historicalWork:historical,currentWork:active,futureWork:[],nextActions,confidenceNote:"Recency alone is not active-work evidence. Facts are deterministic; inferred work remains proposed."};
}
