import type Database from "better-sqlite3";
import type {ProjectMode,RoutingDecision,TrainingExample} from "@ai-pm/shared";
import {newId,now} from "../util.js";
const parse=<T>(v:string):T=>JSON.parse(v) as T;
export function setProjectMode(db:Database.Database,projectId:string,nextMode:ProjectMode,source:"USER_OVERRIDE"|"DETECTED"|"TRANSITION",reason:string,evidence:Record<string,unknown>={}){const row=db.prepare("SELECT project_mode FROM projects WHERE id=?").get(projectId) as {project_mode:string|null}|undefined;if(!row)throw new Error(`Project not found: ${projectId}`);db.transaction(()=>{db.prepare("UPDATE projects SET project_mode=?,project_mode_source=?,updated_at=? WHERE id=?").run(nextMode,source,now(),projectId);db.prepare("INSERT INTO project_mode_events(id,project_id,previous_mode,next_mode,source,reason,evidence_json,created_at) VALUES(?,?,?,?,?,?,?,?)").run(newId(),projectId,row.project_mode,nextMode,source,reason,JSON.stringify(evidence),now());})();return getProjectMode(db,projectId);}
export function getProjectMode(db:Database.Database,projectId:string){const row=db.prepare("SELECT project_mode,project_mode_source FROM projects WHERE id=?").get(projectId) as {project_mode:string|null;project_mode_source:string|null}|undefined;return row?{mode:row.project_mode as ProjectMode|null,source:row.project_mode_source}:null;}
export function listModeEvents(db:Database.Database,projectId:string){return db.prepare("SELECT id,previous_mode previousMode,next_mode nextMode,source,reason,evidence_json evidenceJson,created_at createdAt FROM project_mode_events WHERE project_id=? ORDER BY created_at DESC").all(projectId).map((r:any)=>({...r,evidence:parse(r.evidenceJson)}));}
export interface LearningInput{projectId:string;message:string;stateSummary:Record<string,unknown>;modeEvidence:Record<string,unknown>;routerDecision:RoutingDecision;toolsOffered?:string[];toolsSelected?:string[];actualBehavior?:string;expectedMode:ProjectMode;expectedIntent:string;expectedCapabilities:string[];expectedTools?:string[];forbidden?:string[];failureCategory:string;correctionSource:string;reviewStatus?:string}
export function recordLearningExample(db:Database.Database,i:LearningInput){const id=newId();db.prepare(`INSERT INTO agent_learning_examples(id,project_id,user_message,state_summary_json,mode_evidence_json,router_decision_json,tools_offered_json,tools_selected_json,actual_behavior,expected_mode,expected_intent,expected_capabilities_json,expected_tools_json,forbidden_json,failure_category,correction_source,review_status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,i.projectId,i.message,JSON.stringify(i.stateSummary),JSON.stringify(i.modeEvidence),JSON.stringify(i.routerDecision),JSON.stringify(i.toolsOffered??[]),JSON.stringify(i.toolsSelected??[]),i.actualBehavior??null,i.expectedMode,i.expectedIntent,JSON.stringify(i.expectedCapabilities),JSON.stringify(i.expectedTools??[]),JSON.stringify(i.forbidden??[]),i.failureCategory,i.correctionSource,i.reviewStatus??"UNREVIEWED",now());return id;}
export function reviewLearningExample(db:Database.Database,projectId:string,id:string,status:"APPROVED"|"REJECTED"){return db.prepare("UPDATE agent_learning_examples SET review_status=? WHERE id=? AND project_id=?").run(status,id,projectId).changes>0;}
function sanitize(value:unknown):unknown{if(typeof value==="string"){if(/^[A-Za-z]:\\|^\/|-----BEGIN|(?:token|password|secret|api[_-]?key)\s*[:=]/i.test(value))return "[REDACTED]";return value.slice(0,4000);}if(Array.isArray(value))return value.map(sanitize);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value as Record<string,unknown>).filter(([k])=>!/(secret|token|password|source|path)/i.test(k)).map(([k,v])=>[k,sanitize(v)]));return value;}
export function exportApprovedTrainingData(db:Database.Database,projectId?:string):TrainingExample[]{const rows=db.prepare(`SELECT * FROM agent_learning_examples WHERE review_status='APPROVED' ${projectId?"AND project_id=?":""} ORDER BY created_at`).all(...(projectId?[projectId]:[])) as any[];return rows.map(r=>({id:r.id,projectId:r.project_id,input:{message:sanitize(r.user_message) as string,projectModeEvidence:sanitize(parse(r.mode_evidence_json)) as Record<string,unknown>,projectStateSummary:sanitize(parse(r.state_summary_json)) as Record<string,unknown>},expected:{projectMode:r.expected_mode,intent:r.expected_intent,capabilities:parse(r.expected_capabilities_json),needsRepositoryContext:(parse<RoutingDecision>(r.router_decision_json)).needsRepositoryContext,needsCodeContext:(parse<RoutingDecision>(r.router_decision_json)).needsCodeContext,mutationIntent:(parse<RoutingDecision>(r.router_decision_json)).mutationIntent,tools:parse(r.expected_tools_json)},forbidden:parse(r.forbidden_json),category:r.failure_category,provenance:r.correction_source,reviewStatus:r.review_status,createdAt:r.created_at}));}
export function learningStats(db:Database.Database){const rows=db.prepare("SELECT review_status status,correction_source provenance,failure_category category,COUNT(*) count FROM agent_learning_examples GROUP BY review_status,correction_source,failure_category").all() as any[];return{total:rows.reduce((n,r)=>n+r.count,0),approved:rows.filter(r=>r.status==="APPROVED").reduce((n,r)=>n+r.count,0),groups:rows};}
export function hasLearningExample(db:Database.Database,projectId:string,message:string,category:string){return!!db.prepare("SELECT 1 FROM agent_learning_examples WHERE project_id=? AND user_message=? AND failure_category=? LIMIT 1").get(projectId,message,category);}
