import{afterEach,describe,expect,it}from"vitest";import{execFileSync}from"node:child_process";import fs from"node:fs";import os from"node:os";import path from"node:path";import{createTestDb,intelligenceRepo,projectsRepo}from"@ai-pm/database";import{analyzeBranches,analyzeFileEvolution,clusterQuality,detectTestCommand,fuseEvidence,runDetectedTests}from"../src/lib/evidence-intelligence.js";import{buildRepositorySnapshot}from"../src/lib/intelligence.js";import{clusterRepositoryWork}from"../src/lib/project-understanding.js";
const dirs:string[]=[];afterEach(()=>dirs.splice(0).forEach(d=>fs.rmSync(d,{recursive:true,force:true})));function repo(){const d=fs.mkdtempSync(path.join(os.tmpdir(),"nemo-evidence-"));dirs.push(d);execFileSync("git",["init","-b","main"],{cwd:d});execFileSync("git",["config","user.email","test@nemo.local"],{cwd:d});execFileSync("git",["config","user.name","NEMO"],{cwd:d});return d;}function commit(d:string,file:string,text:string,msg:string,date?:string){const target=path.join(d,file);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,text);execFileSync("git",["add","."],{cwd:d});execFileSync("git",["commit","-m",msg],{cwd:d,env:{...process.env,...(date?{GIT_AUTHOR_DATE:date,GIT_COMMITTER_DATE:date}:{})}});}
describe("evidence intelligence",()=>{
 it("extracts first/last observable file evidence from squash-like history",async()=>{const d=repo();commit(d,"src/auth/login.ts","export{}","baseline snapshot");commit(d,"src/auth/login.ts","export const x=1","audit fix");const snapshot=await buildRepositorySnapshot(d);const evolution=await analyzeFileEvolution(snapshot);const file=evolution.files.find(f=>f.file==="src/auth/login.ts")!;expect(file.firstCommit).not.toBe(file.lastCommit);expect(file.firstSeen).toBeTruthy();expect(evolution.modules.some(m=>m.module==="src/auth")).toBe(true);});
 it("fuses named evidence strengths without hiding them in one score",()=>{const result=fuseEvidence([{type:"MIGRATION",strength:"STRONG",source:"git",detail:"users"},{type:"TEST",strength:"MEDIUM",source:"files",detail:"login"}]);expect(result.confidence).toBe("HIGH_CONFIDENCE");expect(result.summary).toEqual({strong:1,medium:1,weak:0});});
 it("splits large modules hierarchically and reports low-quality clusters",async()=>{const d=repo();commit(d,"src/back/Auth/login.ts","x","add login");commit(d,"src/front/checkout/page.tsx","x","add checkout");const clusters=clusterRepositoryWork(await buildRepositorySnapshot(d));expect(new Set(clusters.map(c=>c.module)).size).toBeGreaterThan(1);expect(clusterQuality({module:"src/back/Api",files:["docs/a.md"],commits:[]} ).flags).toContain("LOW_COHESION");});
 it("classifies merged and diverged branches using unique commits",async()=>{const d=repo();commit(d,"a.txt","a","base");execFileSync("git",["checkout","-b","feature/live"],{cwd:d});commit(d,"b.txt","b","feature");let branches=await analyzeBranches(d);expect(branches.find(b=>b.name==="feature/live")?.state).toBe("ACTIVE_DIVERGED");execFileSync("git",["checkout","main"],{cwd:d});execFileSync("git",["merge","--no-ff","feature/live","-m","merge"],{cwd:d});branches=await analyzeBranches(d);expect(branches.find(b=>b.name==="feature/live")?.state).toMatch(/MERGED|NO_UNIQUE_WORK/);});
 it("classifies old unique branches as stale",async()=>{const d=repo();commit(d,"a.txt","a","base");execFileSync("git",["checkout","-b","feature/old"],{cwd:d});commit(d,"old.txt","x","old","2020-01-01T00:00:00Z");const branch=(await analyzeBranches(d,30)).find(b=>b.name==="feature/old");expect(branch?.state).toBe("STALE_DIVERGED");});
 it("detects tests but does not run them by default",async()=>{const d=repo();fs.writeFileSync(path.join(d,"package.json"),JSON.stringify({scripts:{test:"node test.js"}}));const detected=detectTestCommand(d);expect(detected?.adapter).toBe("NodeTestAdapter");expect((await runDetectedTests(d,detected,{enabled:false})).status).toBe("NOT_RUN");});
 it("captures failure and timeout evidence and rejects arbitrary argv",async()=>{const d=repo();const failing={adapter:"NodeTestAdapter",executable:"node",args:["-e","process.exit(1)"],command:["node","-e","process.exit(1)"],recognized:true};expect((await runDetectedTests(d,failing,{enabled:true,timeoutMs:10_000})).status).toBe("FAIL");const slow={adapter:"NodeTestAdapter",executable:"node",args:["-e","setInterval(function(){},10000)"],command:["node","-e","setInterval(function(){},10000)"],recognized:true};expect((await runDetectedTests(d,slow,{enabled:true,timeoutMs:1_000})).status).toBe("TIMEOUT");expect((await runDetectedTests(d,{adapter:"NodeTestAdapter",executable:"npm",args:["test","; rm"],command:["npm","test","; rm"],recognized:true},{enabled:true})).status).toBe("UNAVAILABLE");},20_000);
 it("stores human review labels and computes precision/recall categories",()=>{const db=createTestDb();const p=projectsRepo.createProject(db,{name:"Review",key:"REV"});intelligenceRepo.recordReview(db,{projectId:p.id,category:"HISTORICAL_WORK",verdict:"CORRECT"});intelligenceRepo.recordReview(db,{projectId:p.id,category:"HISTORICAL_WORK",verdict:"WRONG",falsePositiveCategory:"MODULE_OVER_CLUSTER"});intelligenceRepo.recordReview(db,{projectId:p.id,category:"HISTORICAL_WORK",verdict:"MISSED",missedWorkLabel:"SQUASH_COMMIT"});const m=intelligenceRepo.reviewMetrics(db,p.id);expect(m.historicalWork.precision).toBe(.5);expect(m.historicalWork.recall).toBe(.5);expect(m.falsePositives.MODULE_OVER_CLUSTER).toBe(1);expect(m.missedWork.SQUASH_COMMIT).toBe(1);db.close();});
});
