import{describe,it,expect}from"vitest";import{createTestDb,projectsRepo,learningRepo,repositoriesRepo,issuesRepo,sprintsRepo}from"@ai-pm/database";import{DeterministicRouter,collectModeFeatures,detectProjectMode,reconcileProjectMode,responseContract,type IntentRouter}from"../src/lib/project-mode.js";
const project=(db:any,name="NEMO Hub")=>projectsRepo.createProject(db,{name,key:"HUB"});
describe("NEMO Learning Loop V1",()=>{
it("detects BOOTSTRAP without Git and never requires repository context for MVP planning",()=>{const db=createTestDb(),p=project(db);const f=collectModeFeatures(db,p.id);expect(detectProjectMode(f).mode).toBe("BOOTSTRAP");const r=new DeterministicRouter().route("I want to build NEMO Hub from zero. Help me define the smallest MVP and architecture. Do not create tasks yet.",f);expect(r).toMatchObject({projectMode:"BOOTSTRAP",intent:"bootstrap.define_mvp",needsRepositoryContext:false,mutationIntent:"none"});expect(r.capabilities).toContain("product_planning");db.close()});
it("treats an empty connected repository as BOOTSTRAP, not broken",()=>{const db=createTestDb(),p=project(db);repositoriesRepo.connectRepository(db,p.id,"C:\\safe\\empty");const f=collectModeFeatures(db,p.id);expect(detectProjectMode(f).mode).toBe("BOOTSTRAP");const r=new DeterministicRouter().route("We don't have Git yet. Define the MVP",{...f,repositoryConnected:false});expect(r.projectMode).toBe("BOOTSTRAP");expect(r.needsRepositoryContext).toBe(false);db.close()});
it("distinguishes imported and maintenance situations",()=>{const base={projectCreatedAt:new Date().toISOString(),repositoryConnected:true,repositoryScanned:true,totalIssues:0,activeIssues:0,totalSprints:0,activeSprint:false,completedRatio:0,recentRepositoryActivity:false};expect(detectProjectMode(base).mode).toBe("IMPORTED");expect(detectProjectMode({...base,totalIssues:12,totalSprints:3,completedRatio:.8}).mode).toBe("MAINTENANCE");expect(detectProjectMode(base,"This is an old repository I'm importing").mode).toBe("IMPORTED")});
it("detects ACTIVE work and COMPLETED tracked work",()=>{const db=createTestDb(),p=project(db);const sprint=sprintsRepo.createSprint(db,{projectId:p.id,name:"Sprint 1"});sprintsRepo.startSprint(db,sprint.id);expect(detectProjectMode(collectModeFeatures(db,p.id)).mode).toBe("ACTIVE");const p2=projectsRepo.createProject(db,{name:"Done",key:"DONE"});issuesRepo.createIssue(db,{projectId:p2.id,title:"Delivered",status:"done",type:"task",priority:"medium"});expect(detectProjectMode(collectModeFeatures(db,p2.id)).mode).toBe("COMPLETED");db.close()});
it("persists explicit overrides, audits them, and protects them from automatic transition",()=>{const db=createTestDb(),p=project(db);learningRepo.setProjectMode(db,p.id,"COMPLETED","USER_OVERRIDE","This project is finished");expect(collectModeFeatures(db,p.id).explicitMode).toBe("COMPLETED");expect(reconcileProjectMode(db,p.id).changed).toBe(false);expect(learningRepo.listModeEvents(db,p.id)[0]).toMatchObject({nextMode:"COMPLETED",source:"USER_OVERRIDE"});db.close()});
it("allows only evidence-backed BOOTSTRAP/IMPORTED to ACTIVE transitions",()=>{const db=createTestDb(),p=project(db);learningRepo.setProjectMode(db,p.id,"BOOTSTRAP","DETECTED","new");const sprint=sprintsRepo.createSprint(db,{projectId:p.id,name:"Sprint 1"});sprintsRepo.startSprint(db,sprint.id);expect(reconcileProjectMode(db,p.id)).toMatchObject({changed:true,mode:"ACTIVE"});expect(learningRepo.listModeEvents(db,p.id)[0].previousMode).toBe("BOOTSTRAP");db.close()});
it("uses intent-specific response contracts and removes status bias",()=>{expect(responseContract("bootstrap.define_mvp")).toEqual(["PRODUCT","MVP","NON-GOALS","ARCHITECTURE","EPICS","MILESTONES","OPEN DECISIONS"]);expect(responseContract("bootstrap.define_mvp")).not.toContain("PROGRESS");expect(responseContract("project.status")).toContain("PROGRESS")});
it("captures corrections and exports only approved privacy-safe examples",()=>{const db=createTestDb(),p=project(db);const f=collectModeFeatures(db,p.id),r=new DeterministicRouter().route("Define MVP",f);const base={projectId:p.id,message:"Define MVP; token=secret",stateSummary:{repositoryPath:"C:\\private\\repo",description:"safe"},modeEvidence:f as any,routerDecision:r,expectedMode:"BOOTSTRAP" as const,expectedIntent:"bootstrap.define_mvp",expectedCapabilities:["product_planning"],failureCategory:"WRONG_INTENT",correctionSource:"REAL_USER_CORRECTION"};const rejected=learningRepo.recordLearningExample(db,{...base,reviewStatus:"REJECTED"});const approved=learningRepo.recordLearningExample(db,{...base,reviewStatus:"APPROVED"});const out=learningRepo.exportApprovedTrainingData(db,p.id);expect(out).toHaveLength(1);expect(out[0]!.id).toBe(approved);expect(JSON.stringify(out)).not.toContain("C:\\private");expect(JSON.stringify(out)).not.toContain("token=secret");expect(out.some(x=>x.id===rejected)).toBe(false);db.close()});
it("supports replacement routers behind one interface",async()=>{const db=createTestDb(),p=project(db),f=collectModeFeatures(db,p.id);const replacement:IntentRouter={route:async()=>({projectMode:"BOOTSTRAP",intent:"bootstrap.architecture",capabilities:["architecture"],needsRepositoryContext:false,needsCodeContext:false,mutationIntent:"none",confidence:.9,reason:"test router"})};expect((await replacement.route("x",f)).intent).toBe("bootstrap.architecture");db.close()});
it("routes a diverse deterministic suite with >=97% mode and >=95% intent accuracy",()=>{const db=createTestDb(),p=project(db),f=collectModeFeatures(db,p.id),router=new DeterministicRouter();const cases=[
...Array.from({length:25},(_,i)=>({m:i%2?"New project from zero, define the MVP":"I haven't written code yet. What's the smallest MVP?",mode:"BOOTSTRAP",intent:"bootstrap.define_mvp"})),
...Array.from({length:20},(_,i)=>({m:i%2?"Show project status and progress":"Where are we with progress?",mode:"ACTIVE",intent:"project.status"})),
...Array.from({length:15},(_,i)=>({m:i%2?"Plan the sprint with max 15 points":"Scope the sprint capacity",mode:"ACTIVE",intent:"sprint.plan"})),
...Array.from({length:15},(_,i)=>({m:i%2?"Create a bug issue":"Open a new task",mode:"ACTIVE",intent:"issue.create"})),
...Array.from({length:10},()=>({m:"Explain this code change",mode:"ACTIVE",intent:"code.explain_work"})),
...Array.from({length:10},()=>({m:"Why did we choose this decision?",mode:"ACTIVE",intent:"memory.query"})),
...Array.from({length:10},()=>({m:"Analyze the portfolio",mode:"ACTIVE",intent:"portfolio.analyze"})),
...Array.from({length:20},(_,i)=>({m:i%2?"What are the project risks?":"What are the next actions?",mode:"ACTIVE",intent:i%2?"project.risk":"project.next_actions"}))];
let mode=0,intent=0;for(const c of cases){const features={...f,explicitMode:c.mode as any,activeSprint:c.mode==="ACTIVE"};const r=router.route(c.m,features);if(r.projectMode===c.mode)mode++;if(r.intent===c.intent)intent++;}expect(cases.length).toBeGreaterThanOrEqual(100);expect(mode/cases.length).toBeGreaterThanOrEqual(.97);expect(intent/cases.length).toBeGreaterThanOrEqual(.95);db.close()});
});
