import{afterEach,describe,it,expect}from"vitest";import type{AIProvider,AgentChatInput,ChatInput,StructuredInput}from"@ai-pm/ai";import{AIUnavailableError}from"@ai-pm/ai";import{createTestDb,projectsRepo,sprintsRepo,decisionsRepo,milestonesRepo,learningRepo}from"@ai-pm/database";import{runProjectAgent}from"../src/lib/agent.js";import{setAIProvider}from"../src/lib/ai.js";import{buildPortfolioFallback}from"../src/lib/deterministic-fallback.js";
import{getGitStatus}from"../src/lib/git.js";import fs from"node:fs";import os from"node:os";import path from"node:path";
class OfflineProvider implements AIProvider{async runAgent(_i:AgentChatInput):Promise<never>{throw new AIUnavailableError("offline test")}async chat(_i:ChatInput):Promise<never>{throw new AIUnavailableError("offline test")}async structured<T>(_i:StructuredInput<T>):Promise<T>{throw new AIUnavailableError("offline test")}}
afterEach(()=>setAIProvider(null));
const hub=(db:any)=>projectsRepo.createProject(db,{name:"NEMO Hub",key:"NHUB",description:"Showcase my software projects"});
describe("intent-specific deterministic offline fallback",()=>{
it("keeps the exact NEMO Hub planning route when Ollama is unavailable",async()=>{const db=createTestDb(),p=hub(db);setAIProvider(new OfflineProvider());const result=await runProjectAgent(db,p.id,"I want to start NEMO Hub from zero. Help me define the MVP and architecture.");expect(result.runtime).toMatchObject({projectMode:"BOOTSTRAP",intent:"bootstrap.define_mvp",repositoryContext:false,codeContext:false});expect(result.reply).toMatch(/AI unavailable.*deterministic fallback/i);expect(result.reply).toMatch(/CURRENT STAGE[\s\S]*MVP planning/i);expect(result.reply).toMatch(/KNOWN[\s\S]*Showcase my software projects/i);expect(result.reply).toMatch(/NEXT ACTION/i);expect(result.reply).not.toMatch(/Project Status|0\/0 issues completed|No open work remaining|Reconnect Git/i);expect(result.actions).toHaveLength(0);db.close()});
it("uses a status fallback for an explicit BOOTSTRAP status query",async()=>{const db=createTestDb(),p=hub(db);setAIProvider(new OfflineProvider());const result=await runProjectAgent(db,p.id,"What is the current status of this project?");expect(result.runtime?.intent).toBe("project.status");expect(result.reply).toMatch(/PROJECT STATUS/i);expect(result.reply).toMatch(/No backlog items have been created yet/i);expect(result.reply).not.toMatch(/No open work remaining|not a Git repository|Reconnect Git/i);db.close()});
it("uses status facts for ACTIVE projects",async()=>{const db=createTestDb(),p=hub(db);const s=sprintsRepo.createSprint(db,{projectId:p.id,name:"Sprint 1"});sprintsRepo.startSprint(db,s.id);setAIProvider(new OfflineProvider());const result=await runProjectAgent(db,p.id,"Show project status");expect(result.runtime?.projectMode).toBe("ACTIVE");expect(result.reply).toMatch(/PROJECT STATUS|Project Status/);expect(result.reply).toMatch(/Active: none|Active sprint/i);db.close()});
it("retrieves memory without AI",async()=>{const db=createTestDb(),p=hub(db);decisionsRepo.createDecision(db,p.id,{title:"Use SQLite",decision:"SQLite for local persistence",rationale:"Local first"});setAIProvider(new OfflineProvider());const result=await runProjectAgent(db,p.id,"Why did we choose SQLite?");expect(result.reply).toMatch(/Use SQLite.*SQLite for local persistence/i);expect(result.reply).not.toMatch(/Project Status/);db.close()});
it("returns confirmed history facts and marks synthesis unavailable",async()=>{const db=createTestDb(),p=hub(db);milestonesRepo.createMilestone(db,p.id,{title:"Concept approved",status:"reached",confirmed:true});setAIProvider(new OfflineProvider());const result=await runProjectAgent(db,p.id,"Show project history");expect(result.runtime?.intent).toBe("history.query");expect(result.reply).toMatch(/CONFIRMED HISTORY[\s\S]*Concept approved/);expect(result.reply).toMatch(/synthesis is unavailable/i);db.close()});
it("returns portfolio facts separately from unavailable prioritization",()=>{const db=createTestDb();hub(db);const result=buildPortfolioFallback(db,"offline test");expect(result.reply).toMatch(/FACTS AVAILABLE[\s\S]*Projects: 1/);expect(result.reply).toMatch(/AI PRIORITIZATION UNAVAILABLE/);db.close()});
it("reports precise Git states without conflating missing Git and an uninitialized folder",async()=>{expect(await getGitStatus(null)).toMatchObject({connected:false,errorCode:"NO_REPOSITORY_EXPECTED"});const dir=fs.mkdtempSync(path.join(os.tmpdir(),"nemo-not-git-"));try{expect(await getGitStatus(dir)).toMatchObject({connected:false,errorCode:"REPOSITORY_NOT_INITIALIZED"});expect(await getGitStatus(path.join(dir,"missing"))).toMatchObject({connected:false,errorCode:"REPOSITORY_PATH_INVALID"});}finally{fs.rmSync(dir,{recursive:true,force:true})}});
it("does not treat absent Git or zero issues as completed work in BOOTSTRAP",async()=>{const db=createTestDb(),p=hub(db);setAIProvider(new OfflineProvider());const result=await runProjectAgent(db,p.id,"Define the MVP for this new project");expect(result.reply).toMatch(/No backlog items have been created yet/);expect(result.reply).not.toMatch(/No open work remaining|Git.*risk|Reconnect Git/i);db.close()});
it("preserves the route across an AI timeout and captures the real regression once",async()=>{const db=createTestDb(),p=hub(db);setAIProvider(new OfflineProvider());const message="I want to start NEMO Hub from zero. Help me define the MVP and architecture.";const first=await runProjectAgent(db,p.id,message),second=await runProjectAgent(db,p.id,message);expect(first.runtime?.intent).toBe("bootstrap.define_mvp");expect(second.runtime?.intent).toBe("bootstrap.define_mvp");const stats=learningRepo.learningStats(db);expect(stats.total).toBe(1);expect(stats.groups[0]).toMatchObject({status:"UNREVIEWED",provenance:"REGRESSION_CASE",category:"BAD_FINAL_RESPONSE"});expect(learningRepo.exportApprovedTrainingData(db,p.id)).toHaveLength(0);db.close()});
});
