import{afterEach,describe,expect,it}from"vitest";import fs from"node:fs";import os from"node:os";import path from"node:path";import{createTestDb,intelligenceRepo,projectsRepo}from"@ai-pm/database";import{discoverTestSuites}from"../src/lib/evidence-intelligence.js";
const dirs:string[]=[];afterEach(()=>dirs.splice(0).forEach(dir=>fs.rmSync(dir,{recursive:true,force:true})));
describe("ground-truth calibration",()=>{
 it("keeps reviews project-scoped and empty datasets unmeasured",()=>{const db=createTestDb();const a=projectsRepo.createProject(db,{name:"A",key:"A"});const b=projectsRepo.createProject(db,{name:"B",key:"B"});expect(intelligenceRepo.evaluationMetrics(db,a.id).status).toBe("NOT_MEASURED");intelligenceRepo.recordReviewV2(db,{projectId:a.id,category:"CURRENT_WORK",verdict:"CORRECT",impact:"HIGH"});expect(intelligenceRepo.listReviewsV2(db,a.id)).toHaveLength(1);expect(intelligenceRepo.listReviewsV2(db,b.id)).toHaveLength(0);db.close();});
 it("stores all labels, missed items, corrections and impact-weighted metrics",()=>{const db=createTestDb();const p=projectsRepo.createProject(db,{name:"Review",key:"REV"});intelligenceRepo.recordReviewV2(db,{projectId:p.id,findingId:"h1",category:"HISTORICAL_WORK",verdict:"CORRECT",confidence:.97,impact:"HIGH",evidence:["commit"],correctedTitle:"Auth"});intelligenceRepo.recordReviewV2(db,{projectId:p.id,findingId:"h2",category:"HISTORICAL_WORK",verdict:"PARTIALLY_CORRECT",confidence:.88,impact:"LOW",correctedCluster:"Split auth"});intelligenceRepo.recordReviewV2(db,{projectId:p.id,findingId:"h3",category:"HISTORICAL_WORK",verdict:"WRONG",confidence:.96,impact:"LOW",falsePositiveCategory:"MODULE_OVER_CLUSTER"});intelligenceRepo.recordReviewV2(db,{projectId:p.id,category:"HISTORICAL_WORK",verdict:"MISSED",impact:"HIGH",reviewKind:"MISSED_ITEM",missedWorkLabel:"SQUASH_HISTORY",inference:{title:"Payments"}});const m=intelligenceRepo.evaluationMetrics(db,p.id);expect(m.historicalWork.raw.precision).toBeCloseTo(2/3);expect(m.historicalWork.raw.recall).toBeCloseTo(2/3);expect(m.historicalWork.impactWeighted.precision).toBeCloseTo(5/6);expect(m.falsePositives.MODULE_OVER_CLUSTER).toBe(1);expect(m.missedWork.SQUASH_HISTORY).toBe(1);expect(m.confidenceCalibration.find(x=>x.bucket==="95-100")?.reviewCount).toBe(2);db.close();});
 it("calibrates AUTO actions, proposals, clusters and exports the dataset",()=>{const db=createTestDb();const p=projectsRepo.createProject(db,{name:"Calibration",key:"CAL"});intelligenceRepo.recordReviewV2(db,{projectId:p.id,category:"CURRENT_WORK",verdict:"CORRECT",reviewKind:"AUTO_ACTION",autoVerdict:"CORRECT"});intelligenceRepo.recordReviewV2(db,{projectId:p.id,category:"NEXT_ACTION",verdict:"PARTIALLY_CORRECT",reviewKind:"PROPOSAL",proposalOutcome:"EDITED"});intelligenceRepo.recordReviewV2(db,{projectId:p.id,category:"HISTORICAL_WORK",verdict:"WRONG",reviewKind:"CLUSTER",clusterVerdict:"SHOULD_SPLIT",falsePositiveCategory:"MODULE_OVER_CLUSTER"});const m=intelligenceRepo.evaluationMetrics(db,p.id);expect(m.autoActions.precision).toBe(1);expect(m.proposals.editRate).toBe(1);expect(m.clusterApprovalRate).toBe(0);const exported=intelligenceRepo.exportReviewDataset(db,p.id);expect(exported.reviews).toHaveLength(3);expect(exported.projectId).toBe(p.id);db.close();});
 it("discovers bounded nested monorepo test suites",()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"nemo-workspaces-"));dirs.push(dir);fs.mkdirSync(path.join(dir,"apps","web"),{recursive:true});fs.mkdirSync(path.join(dir,"packages","core"),{recursive:true});fs.writeFileSync(path.join(dir,"package.json"),JSON.stringify({workspaces:["apps/*","packages/*"]}));fs.writeFileSync(path.join(dir,"apps","web","package.json"),JSON.stringify({scripts:{test:"vitest run"}}));fs.writeFileSync(path.join(dir,"packages","core","package.json"),JSON.stringify({scripts:{build:"tsc"}}));const suites=discoverTestSuites(dir);expect(suites.find(s=>s.relativePath==="apps/web")?.detected?.adapter).toBe("NodeTestAdapter");expect(suites.find(s=>s.relativePath==="packages/core")?.detected).toBeNull();});
 it("does not mark metrics measured until the review target is reached",()=>{const db=createTestDb();const p=projectsRepo.createProject(db,{name:"Target",key:"TGT"});for(let i=0;i<100;i++)intelligenceRepo.recordReviewV2(db,{projectId:p.id,findingId:`f${i}`,category:"PROJECT_UNDERSTANDING",verdict:i%10===0?"WRONG":"CORRECT",confidence:.95,impact:"MEDIUM"});const m=intelligenceRepo.evaluationMetrics(db,p.id);expect(m.status).toBe("MEASURED");expect(m.projectUnderstanding.raw.precision).toBe(.9);expect(m.falsePositiveRate).toBe(.1);db.close();});
});
