import{afterAll,beforeAll,describe,it,expect}from"vitest";import type{FastifyInstance}from"fastify";import type{AIProvider,AgentChatInput,AgentTurnResult,ChatInput,ChatResult,StructuredInput}from"@ai-pm/ai";
process.env.DATABASE_PATH=":memory:";
class OnlineProvider implements AIProvider{lastAgent:AgentChatInput|null=null;agentReply="";chatReply="";async runAgent(input:AgentChatInput):Promise<AgentTurnResult>{this.lastAgent=input;return{text:this.agentReply,toolCalls:[],model:"online-mock",modelCalls:1}}async chat(_input:ChatInput):Promise<ChatResult>{return{text:this.chatReply||this.agentReply,model:"online-mock"}}async structured<T>(_input:StructuredInput<T>):Promise<T>{throw new Error("unused")}}
let app:FastifyInstance,provider:OnlineProvider,projectId:string,closeDb:()=>void;
beforeAll(async()=>{const dbm=await import("@ai-pm/database");closeDb=dbm.closeDb;dbm.getDb();const ai=await import("../src/lib/ai.js");provider=new OnlineProvider();ai.setAIProvider(provider);const{buildServer}=await import("../src/app.js");app=buildServer();await app.ready();projectId=(await app.inject({method:"POST",url:"/projects",payload:{name:"NEMO Hub",key:"NHUB",description:"Personal hub showcasing software projects"}})).json().id});
afterAll(async()=>{const{setAIProvider}=await import("../src/lib/ai.js");setAIProvider(null);await app.close();closeDb()});
describe("real Web Agent endpoint online regression",()=>{
it("keeps BOOTSTRAP planning out of the legacy status contract",async()=>{provider.agentReply="Progress\n0/0 issues completed\n\nCurrent work\nNone\n\nRecent activity\nNo commits\n\nRisk\nNo Git repository\n\nRecommendation\nInitialize a new Git repository.";provider.chatReply="PRODUCT\nNEMO Hub is a personal software-project showcase.\n\nMVP\nA visitor can view a concise list of projects and open one project detail page.\n\nNON-GOALS\nAccounts, analytics, and collaboration.\n\nARCHITECTURE\nOne web application with static project data first.\n\nOPEN DECISIONS\nHosting and project data format.";const message="I want to start NEMO Hub from zero. It's a personal hub where I can showcase all my software projects. Help me define the smallest useful MVP and architecture. Keep it simple for one developer. Do not create tasks or a sprint yet.";const res=await app.inject({method:"POST",url:`/projects/${projectId}/agent`,payload:{message}});expect(res.statusCode).toBe(200);const body=res.json();expect(body.runtime).toMatchObject({projectMode:"BOOTSTRAP",intent:"bootstrap.define_mvp",repositoryContext:false,codeContext:false});expect(body.runtime.toolsOffered).toEqual([]);expect(body.reply).toMatch(/^PRODUCT/m);expect(body.reply).not.toMatch(/^Progress|^Current work|^Recent activity|^Risk(?:s)?|^Recommendation|initialize a new Git repository/im);const userPrompt=provider.lastAgent!.messages.find(m=>m.role==="user")!.content;expect(userPrompt).not.toMatch(/Git repository|0\/0|No issues|Recent activity|Recommendation/);expect(userPrompt).toMatch(/Project mode: BOOTSTRAP/);expect(userPrompt).toMatch(/Decisions \(0; showing 0\):[\s\S]*None loaded/);expect(userPrompt).toMatch(/Milestones \(0; showing 0\):[\s\S]*None loaded/)});
it("uses one model call with no redundant tools for sufficient Bootstrap context",async()=>{provider.agentReply="PRODUCT\nA focused personal project showcase.\n\nMVP\nProject index and project detail pages.\n\nNON-GOALS\nAccounts and collaboration.\n\nARCHITECTURE\nOne web app with local structured data.\n\nEPICS\nShowcase browsing.\n\nMILESTONES\nFirst deployable showcase.\n\nFIRST VERTICAL SLICE\nRender one stored project end to end.\n\nOPEN DECISIONS\nHosting and data format.";provider.chatReply="";const res=await app.inject({method:"POST",url:`/projects/${projectId}/agent`,payload:{message:"I want to start this project from zero. Help me define the smallest useful MVP and architecture."}});const body=res.json();expect(body.runtime).toMatchObject({projectMode:"BOOTSTRAP",intent:"bootstrap.define_mvp",repositoryContext:false,codeContext:false,modelCalls:1});expect(body.runtime.toolsOffered).toEqual([]);expect(provider.lastAgent?.tools).toHaveLength(0);for(const heading of ["PRODUCT","MVP","NON-GOALS","ARCHITECTURE","EPICS","MILESTONES","FIRST VERTICAL SLICE","OPEN DECISIONS"])expect(body.reply).toMatch(new RegExp(`^${heading}$`,"m"));});
it("allows the status template only for project.status",async()=>{provider.agentReply="Progress\nPlanning has started.\n\nCurrent work\nProduct definition.\n\nRecent activity\nNo planning records yet.\n\nRisk\nNone recorded.\n\nRecommendation\nDefine the MVP.";provider.chatReply="";const res=await app.inject({method:"POST",url:`/projects/${projectId}/agent`,payload:{message:"What is the current status of this project?"}});const body=res.json();expect(body.runtime).toMatchObject({projectMode:"BOOTSTRAP",intent:"project.status"});expect(body.reply).toMatch(/^Progress/m);expect(body.reply).toMatch(/^Recommendation/m)});
});
